### ISSUE TITLE
v1.0.0 causes compiling with `via-ir` to take substantially longer

### ISSUE THREAD

**Issue by Vectorized** [foundry-rs/forge-std#207] opened 2022-11-03 14:35 UTC
Recently, I added a `via-ir` testing to Solady for more robust testing, since it is a library.

However, with the latest version of forge-std, the CI is still unable to finish compiling the code after 30 minutes.

See this workflow run: https://github.com/Vectorized/solady/actions/runs/3385556435/jobs/5623841631 (not complete even after 30 minutes)

I left it compiling for more than 3 hours on my machine, to no avail too.

Reverting back `forge-std` to an eariler commit `c19dfd2f2a88a461216b0dd1f4961e1a85dcad46` seems to solve the issue.  

See this workflow run:  https://github.com/Vectorized/solady/actions/runs/3386504801/jobs/5625994122 (completes under 2 minutes)

**Comment by leonardoalt** [comment] 2022-11-03 14:39
Does the Solidity version also change between the two tests?

**Comment by mds1** [comment] 2022-11-03 14:47
It looks like they're both 0.8.17

Successful one:
<img width="691" alt="image" src="https://user-images.githubusercontent.com/17163988/199753238-403d719c-065f-44cf-bf69-422fcb2eabcf.png">

Failed one 
<img width="675" alt="image" src="https://user-images.githubusercontent.com/17163988/199753173-429e5446-ee6a-4f29-ba75-9be61c9f28e2.png">

**Comment by jameswenzel** [comment] 2022-11-03 15:19
I stumbled across this thread from the Seaport release - I don't fully follow the thread, but it seems like `via-ir` slowness isn't an issue with other `solc` compilers, just the one supplied by `svm-rs` – which means at least part of this slowness is probably due an upstream `foundry` or `svm-rs` issue?
https://github.com/ethereum/solidity/issues/13050

**Comment by Vectorized** [comment] 2022-11-03 17:50
Looks like compiling forge-std alone with `via-ir` takes incredibly long since the v1.0.0 commit.

The previous commit `2a2ce3692b8c1523b29de3ec9d961ee9fbbc43a6`, still compiles reasonably fast.

**Comment by Vectorized** [comment] 2022-11-03 18:03
Update: looks like commit `72cdd70ae608e32711b4bcf3bbcdafc9eddc3c56` in `v0.3` is the start of the insanely long compile times.

**Comment by mattsse** [comment] 2022-11-03 18:32
> I don't fully follow the thread, but it seems like via-ir slowness isn't an issue with other solc compilers

Do you mean different solc versions?

what's your OS?

**Comment by Vectorized** [comment] 2022-11-03 18:33
@mattsse @leonardoalt @mds1 See my previous comment.

**Comment by mattsse** [comment] 2022-11-03 18:33
we're _only_ talking about solc compile times, right?

**Comment by mattsse** [comment] 2022-11-03 18:35
can you try this locally and check when you notice it (during or after the compile spinner?). I suspect this is actually testing not compiling.

**Comment by Vectorized** [comment] 2022-11-03 18:39
I'm using Ubuntu 20.04.4 LTS.

Both `forge build --via-ir` and `forge test --via-ir` takes incredibly long.

**Comment by mds1** [comment] 2022-11-03 18:41
@Vectorized yea I've confirmed that commenting out the `_constructor` logic speeds up the compile times. @leonardoalt any idea why that block would cause such a performance impact? I haven't yet dug in to see if there's a specific section of that method that's problematic

@Vectorized wdym by "changed the constructor into a lazy initializer and the compilation went under a minute"? like you moved that into a function that needs to be explicitly called instead of running at construction?

**Comment by Vectorized** [comment] 2022-11-03 18:43
@mds

```solidity
bool private lazyInitialized;

function lazyInitialize() private {
    if (lazyInitialized) return;
    lazyInitialized = true;
    ...
}

function assumeNoPrecompiles(address addr, uint256 chainId) internal virtual {
    lazyInitialize();
    ...
}
```

Caveat is you can't use `stdChains` without calling a getter function.

**Comment by Vectorized** [comment] 2022-11-03 18:45
Imo, the greatly improved compilation time for `via-ir` CI pipelines is worth the drop in syntactic sugar.

**Comment by leonardoalt** [comment] 2022-11-03 20:46
Ok definitely something weird with `solc`:

Inside `forge-std`, running the command below finishes in one second.
```bash
solc --base-path . --bin --via-ir --optimize src/Test.sol
```
Now create a file `src/a.sol`:
```solidity
import "../src/Test.sol";
contract C is Test {}
```
and run
```bash
solc --base-path . --bin --via-ir --optimize src/a.sol
```

this now hangs.

**Comment by leonardoalt** [comment] 2022-11-03 20:53
Ok actually the thing above is just because `Test` is `abstract`. If it's not abstract it also hangs.

**Comment by leonardoalt** [comment] 2022-11-03 20:57
Ok that's just because `Test` is abstract though. If it's not abstract it takes 40s, but does finish.

**Comment by mds1** [comment] 2022-11-03 23:23
So if I build via forge, it takes ~900 seconds. If I run `solc --base-path . --bin --via-ir --optimize src/Test.sol` it takes 88 seconds... 🤔

**Comment by jameswenzel** [comment] 2022-11-04 00:59
> > I don't fully follow the thread, but it seems like via-ir slowness isn't an issue with other solc compilers
> 
> Do you mean different solc versions?
> 
> what's your OS?

I mean solc binary distributions - from issue I linked issue, @hrkrshnn pointed out that the Rust solc binaries that `svm-rs` uses have debug symbols included – not sure what that means in practice, though, other than maybe being less optimal?

**Comment by leonardoalt** [comment] 2022-11-04 07:26
> So if I build via forge, it takes ~900 seconds. If I run `solc --base-path . --bin --via-ir --optimize src/Test.sol` it takes 88 seconds... 🤔

Yea, also have that. Maybe forge is just trying to compile other stuff too that always get similarly stuck? I'm also trying this only on forge-std, it's enough to replicate.

**Comment by mds1** [comment] 2022-11-04 18:53
@mattsse is there a way to only compile a single contract with `forge build`? I guess you could use the `--skip` flag and skip everything else but that seems tedious. But I guess this means the two possible sources of error are:
1. Something in forge
2. The solc binaries used/built by svm-rs differ somehow, since I think for some versions @roynalnaruto builds the binaries?

**Comment by mds1** [comment] 2022-11-07 14:33
@roynalnaruto Are all svm-rs binaries directly from https://binaries.soliditylang.org/ or are some custom compiled?

**Comment by roynalnaruto** [comment] 2022-11-08 01:33
Binaries for Mac M1 (`macos:aarch64`) and Linux Aarch64 (`linux:aarch64`) are custom compiled, more info in [this repo](https://github.com/roynalnaruto/solc-builds) and [this repo](https://github.com/nikitastupin/solc) respectively.

For other targets, they're fetched from [binaries.soliditylang](https://binaries.soliditylang.org/).

**Comment by mattsse** [comment] 2022-11-08 08:47
I wasn't able to reproduce this on solady master (the branch that belongs to the linked CI run is deleted so assuming it was merged)

```
FOUNDRY_PROFILE=via-ir forge test --force                                                            
[⠊] Compiling...
[⠆] Compiling 65 files with 0.8.17
[⠃] Solc 0.8.17 finished in 154.27s
Compiler run successful
```


but was able to reproduce the behavior @leonardoalt described, with solc 0.8.17 on intel mac.
and tracked this down to `StdCheatsSafe`

 > And it seems we can rule out an underlying solc error given the speed when invoking solc directly

since this happens when invoking solc directly, I don't think this is correct.

I thought we already identified the `_constructor()` call as the root cause?

> So if I build via forge, it takes ~900 seconds. If I run solc --base-path . --bin --via-ir --optimize src/Test.sol it takes 88 seconds... 🤔

`Test` is an abstract contract, so perhaps this plays a role here, because

```
solc --base-path . --bin --via-ir --optimize src/a.sol
``` 

hangs for `a.sol`:

```solidity
import "./Test.sol";
contract C is Test {}
```

**Comment by leonardoalt** [comment] 2022-11-08 09:37
Yea exactly, you need to make Test non abstract to make it take long. This seems to be some edge case in the optimizer, someone from Solidity is already taking a look.

**Closed** 2022-11-11 18:26 UTC
