### ISSUE TITLE
first key in a mapping with type uint as key does allow to access zero key

### ISSUE THREAD

**Issue by FredCoen** [foundry-rs/forge-std#26] opened 2022-03-10 18:16 UTC
mapping(uint=> address) ownerOf

trying to get storage slot of key 0 doesnt work, complains about index out of bounds
```
uint256 slotOfNewOwner = stdstore
            .target(address(nft))
            .sig(nft.ownerOf.selector)
            .with_key(0)
            .find();
```
instead accessing key 0 the following way works:
```
uint256 slotOfNewOwner = stdstore
            .target(address(nft))
            .sig(nft.ownerOf.selector)
            .with_key(1)
            .find();
```

**Comment by ZeroEkkusu** [comment] 2022-04-16 13:44
Std-storage is working as intended (no index oob issues).

I could not replicate the error back when you first posted this and it works fine now as well.

Closing now. Please reply if this still is an issue for you.

**Closed by ZeroEkkusu** 2022-04-16 13:44 UTC
