### ISSUE TITLE
Tests: find a way to strengthen/speed up RPC-related tests

### ISSUE THREAD

**Issue by Evalir** [foundry-rs/forge-std#363] opened 2023-04-28 00:44 UTC
Right now, due to the specific `can_test_forge_std` test on foundry, CI takes extremely long—today it just hanged up. Therefore as a quick measure https://github.com/foundry-rs/forge-std/pull/364 was put up to comment it out. However, we should find a stronger way to fix & speed up these tests so that they take less time.

**Comment by 0xMelkor** [comment] 2023-04-28 15:47
Running tests locally it hangs on the `createSelectFork` cheat code

**Comment by Evalir** [comment] 2023-04-28 15:56
Hmm that makes sense yes—if we see the failed tests on the CI, it fails to instantiate forks—but I suspect it's not the cheatcode itself, but rather the rpc keys being used. Also unsure why CI is still taking so long even though the flaky test was commented out

**Comment by 0xMelkor** [comment] 2023-04-28 16:58
You are right @Evalir. With a different Infura key my local `createSelectFork` tests work.
Let me inspect what magic is behind  the CI slowness...

**Comment by 0xMelkor** [comment] 2023-04-28 17:53
The problem is at [cli/tests/it/test_cmd.rs:L296](https://github.com/foundry-rs/foundry/blob/91f2a442119106a4b2b0cc639e5a01d542294fdb/cli/tests/it/test_cmd.rs#L296) 

This function is called by CI and initializes a local forge project, including the `forge-std` library. Such library still contains hanging RPC endpoints.

<img width="746" alt="Schermata 2023-04-28 alle 19 44 18" src="https://user-images.githubusercontent.com/8720857/235217365-d3b17c34-06c6-470c-8b29-358db7d43ce4.png">

Logs here also confirm my hypothesis:
https://github.com/foundry-rs/foundry/actions/runs/4828234279/jobs/8610628172?pr=4744

Does it make sense?

**Comment by Evalir** [comment] 2023-04-29 05:00
Yep—this macro creates an initialized foundry project with forge-std installed. However the issue should still be the RPC endpoints. The weird thing is supposedly the flaky test was commented out therefore CI should run faster, but it's still pretty slow over at foundry. Shouldn't be the case

**Comment by 0xMelkor** [comment] 2023-04-29 07:28
CI is not using your patch (#364).

CI runs `forge-init`, that sticks to the latest `forge-std` tag (currently `v1.5.4`). 

I think adding a new tag would help.

**Comment by Evalir** [comment] 2023-04-29 07:30
Ahhh good observation actually cc @mds1 this is why it was still a tad slow—we need to roll out a new `forge-std` so changes take place. https://github.com/foundry-rs/foundry/pull/4851 should also help a bit going forward

**Comment by mds1** [comment] 2023-04-30 14:04
Hm it looks like we still have slow CI if one of the mainnet infura RPC we use in other tests doesn't work. I noticed https://github.com/foundry-rs/foundry/pull/4781 so just merged https://github.com/foundry-rs/forge-std/pull/368, and put out a new release (v1.5.5), so this should help the upstream tests

**Comment by Evalir** [comment] 2023-05-21 21:44
I think we could close this now? CI speed has improved a bit since we opened this issue

**Comment by mds1** [comment] 2023-05-22 00:54
Yea I'm ok with keeping that test commented out, since it will always be flaky by nature of using public RPCs

**Closed by mds1** 2023-05-22 00:54 UTC
