### ISSUE TITLE
"ds-test/test.sol" Not Found

### ISSUE THREAD

**Issue by SARNAVOSS** [foundry-rs/forge-std#506] opened 2024-02-06 16:37 UTC
import {DSTest} from "ds-test/test.sol";

"ds-test/test.sol" :- doesn't exsist

**Comment by mds1** [comment] 2024-02-06 17:33
Please provide steps to reproduce

**Comment by zhouyong0115** [comment] 2024-04-16 12:04
Me too. When i complied "lib/forge-std/src/Test.sol" in remix, And it response me "Error: not found ds-test/test.sol". I hava already placed the test.sol file in the expected directory, however it doesn't work.  
And another problem, it shows 'stack too deep' when compiling the file in "src/P256Verifier.sol", and here are the detials.
*******************************
CompilerError: Stack too deep. Try compiling with `--via-ir` (cli) or the equivalent `viaIR: true` (standard JSON) while enabling the optimizer. Otherwise, try removing local variables.
   --> src/P256Verifier.sol:326:54:
    |
326 |         uint256 comp_M = addmod(mulmod(3, mulmod(x1, x1, p), p), mulmod(a, mulmod(zz1, zz1, p), p), p); //M = 3*(X1)^2 + a*(zz1)^2
    |                                                      ^^

**Comment by mds1** [comment] 2024-04-16 23:31
versions 1.8.0 and later of forge-std removed ds-test as a dependency, but earlier versions have it.  The stack too deep error is not a foundry issue, but specific to the P256Verifier contract. Closing since everything seems to be working as expected from my testing, but if you are still having issues provide concrete steps to reproduce (e.g. how are you getting forge-std into remix?) and I may be able to help

**Closed by mds1** 2024-04-16 23:31 UTC
