### ISSUE TITLE
Question about vm.prank limitations

### ISSUE THREAD

**Issue by sunbreak1211** [foundry-rs/forge-std#451] opened 2023-09-04 19:48 UTC
It's true that `vm.prank` and `vm.startPrank` do not specify anything about what happens with `address(this)`, however this behavior is a bit weird:
```vm.startPrank(address(123));
assertEq(address(this), address(123)); => fails
```
There is a concrete case where this is hitting us. We are trying to test a library which we will use in a certain context, where an action needs to happen using `address(this)`.

So our code looks something like this:
```
vm.startPrank(address(123));
libraryContract.callFunction(...); (internal call)
``` 

The call to the library executes any external call (in its code) with `address(123)` as `msg.sender`, which is good. However as we also have some logic in the library function that makes usage of `address(this)`, this gets messy.
I'm not sure if prank could be extended to also modify `address(this)`, or maybe have a different `cheatcode` for this.

**Comment by mds1** [comment] 2023-09-05 19:52
The recommended approach here is to not test internal library calls directly like shown above, but instead wrap them in a test harness. That way, all usage of your library is via external calls, meaning all cheatcodes work as intended. I'm going to close this, but feel free to ask any followup questions :)

```solidity
// src/Foo.sol
library Foo {
  function bar(uint256 x) internal {
    // --- snip ---
  }
}

// test/Foo.t.sol
contract FooHarness {
  function exposed_bar(uint256 x) external {
    Foo.bar(x);
  }
}

contract FooTest is Test {
  FooHarness foo;

  function setUp() external {
    foo = new FooHarness();
  }

  function test_Bar() external {
    vm.startPrank(address(123));
    foo.exposed_bar(x);
  }
}
```

**Closed by mds1** 2023-09-05 19:52 UTC
