### ISSUE TITLE
Issues with dealERC721

### ISSUE THREAD

**Issue by stevennevins** [foundry-rs/forge-std#317] opened 2023-03-01 20:42 UTC
I was testing out the new deal features in v1.5.0 and ran into issues with dealERC721

Using dealERC721 reverts with `StdCheats deal(address,address,uint,bool): id not minted.] `

[Minimal repo ](https://github.com/stevennevins/forge-std_testDeal)demonstrating behavior.  The deal functions for ERC20 and ERC1155 seem to work as expected but not ERC721

**Comment by mds1** [comment] 2023-03-01 23:09
cc @wirew0lf any chance you could take a look?

**Comment by wirew0lf** [comment] 2023-03-01 23:13
Hey @stevennevins is the token you are trying to deal already minted? This message is usually because currently `dealERC721` doesn't allow the deal of tokens which have not been previously minted for a number of reasons.

**Comment by stevennevins** [comment] 2023-03-02 00:00
Doesn’t that deviate from how the other two deal functions operate? 

It seems like more intuitive UX would be to deal an id to an account if it hasn’t previously been minted

**Comment by wirew0lf** [comment] 2023-03-02 00:16
This is due to a limitation in foundry right now. The deal tokens work by targetting some of the functions through StdStorage in order to retrieve the storage slot for the `_owners` mapping and overwrite it. If the token id hasn't been previously minted the slot is packed and overwriting a packed slot is currently not supported by the StdStorage library, that's why I implemented the require statement where you are getting the revert, so this could be more concise for the user.

For instance this is what would happen if you tried to overwrite a non-existing token without that require:
<img width="1473" alt="image" src="https://user-images.githubusercontent.com/11537225/222296787-c861bc59-36bc-4959-ac35-c6d1f13ac911.png">

Unfortunately there's not much we can do right now to overcome this afaik.

**Comment by wirew0lf** [comment] 2023-03-02 00:23
> Doesn’t that deviate from how the other two deal functions operate?

Also it is important to note that ERC20 behaves quite different than ERC721, on ERC20 we only care about the balance for each user and we can easily alter that without having to manually mint tokens. For ERC721 only a single user can own a given token id, and that token must be minted previously for someone to own it. ERC1155 is more similar to ERC20 and as multiple users can own different amounts of a same token id.

So while I see the point where the more intuitive UX is for all deals to work similarly it is difficult as each ERC behaves in a different way, specially ERC721.

**Comment by stevennevins** [comment] 2023-03-02 02:40
Couldn't it look something like [this](https://github.com/stevennevins/forge-std/commit/418596078ea6e97e12d13ae5591f664b8de5a53f)

**Comment by wirew0lf** [comment] 2023-03-02 08:13
> Couldn't it look something like [this](https://github.com/stevennevins/forge-std/commit/418596078ea6e97e12d13ae5591f664b8de5a53f)

That code would not work with a standard ERC721 implementantion.


- On openzeppelin's ERC721 calling the `ownerOf()` function will revert if the token has not been previously minted (owner = address(0)). For this reason we are checking call sucess. Otherwise transaction would revert on the call and wouldn't even reach that require statement.

  <img width="511" alt="image" src="https://user-images.githubusercontent.com/11537225/222368144-6c9c99a5-228c-43e1-a927-9ce6e824d2eb.png">

  https://github.com/stevennevins/forge-std/blob/418596078ea6e97e12d13ae5591f664b8de5a53f/src/StdCheats.sol#L607

- You are removing the part where we substract the token from the previous owner's balance. An ERC721 can only have one owner at a given time, so it makes sense when you deal it to another address remove it from the previous owner balance. On ERC721 the sum of all balances must be equal to the amount of tokens minted, by removing that code you are breaking this invariant, which imo is not ideal.

- This wouldn't solve the limitation of dealing non-minted tokens as this is a limitation on overwriting packed slots of StdStorage and not a limitation of the `dealERC721` function.

**Comment by stevennevins** [comment] 2023-03-02 17:33
Makes sense, yeah seems like there are a lot of constraints here.
-  I'm not sure what to do about the first point.  Might try looking more in-depth look next week after ETH Denver. 
- This was intentional.  Honestly i don't think you should be able to deal an ERC721 that was previously minted and held by another address.  In my example, I added a revert if the id was already minted so I didn't need to update any from balance.
- I think this might be because your bytes4 value that you're trying to write with isn't correct.

I think this can be closed due to various limitations that exist. But just to highlight, I think the behavior should be updated to deal an ERC721 that hasn't been previously minted.  The requirement to mint prior to dealing defeats a lot of the benefits of the cheatcode.

**Comment by wirew0lf** [comment] 2023-03-02 18:38
> * This was intentional.  Honestly i don't think you should be able to deal an ERC721 that was previously minted and held by another address.  In my example, I added a revert if the id was already minted so I didn't need to update any from balance.

I guess this depends on the use case, for my case for example I usually only use this for tokens that have been previously minted. I work as an auditor and often find myself doing pocs with specific tokens that already belong to an address in a forked environment, it is useful for me then.



> * I think this might be because your bytes4 value that you're trying to write with isn't correct.

The function signature is correct. I get your point and what I think would be ideal for this cheatcode is to be able to deal a token, doesn't mind if it was previously minted or not. If it was minted then update the balance of the previous owner and if it was not then just add it to the destination balance.

The problem is as I said earlier, this limtiation was not based on a UX decision but a techincal limitation, we currenlty have no way to write to packed slots, therefore we can only deal tokens which already belong to a user as those are already written to a storage slot and we can easily overwrite them.

**Comment by mds1** [comment] 2023-03-02 19:41
Closing per the above discussion, thanks all

**Closed by mds1** 2023-03-02 19:41 UTC

**Comment by wirew0lf** [comment] 2023-03-06 13:17
I forgot to mention, I will add support for dealing non-minted ERC721 tokens once #148 is done and we can write to packed slots.
